### PR TITLE
accomodate GoogleCloudPlatform/kubernetes#6380 [RFC/quick hack]

### PR DESCRIPTION
**Pull request by AntonioMeireles**
this *works*, not sure if this a good idea, as is, as probably
one should look at both new (10248) and previous (10250) ports
for /healthz. OTOH one can now set *a la carte* healthz ports in
the minions' kubelet ( via --healthz_port ) so one must also
handle that, long term.

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
cc @pires

**Comment by kelseyhightower** [comment]
@AntonioMeireles Maybe we need to make this port configurable?

**Comment by AntonioMeireles** [comment]
@kelseyhightower makes sense, and that crossed my mind. the only issue is that on paper nothing forces all the minions of a cluster to have the /healthz port setup in same way (it wouldn't be too sane, but at my age i've already seen enough to think about that as a plausible scenario).

So, we could go for the common case - all minions have /healthz setup in similar way and tell just that at startup time to kube-register.  And eventually (perhaps via fleet/etcd)? later we could try (if we care enough) about handling remaining corner cases... what do you think ?

**Comment by kelseyhightower** [comment]
@AntonioMeireles Fixed here: https://github.com/kelseyhightower/kube-register/commit/3198c4379c1f642b417bc82fad23d129b5e70e37

**Comment by kelseyhightower** [comment]
@AntonioMeireles We also need to consider supporting v1beta3 API endpoint as well.

**Comment by AntonioMeireles** [comment]
closing via kelseyhightower/kube-register@3198c43. [cf. GoogleCloudPlatform/kubernetes#6851]

**Pull request closed without merging**
